### PR TITLE
Prevent processor from getting stuck

### PR DESCRIPTION
**Pull request by nicolaasmatthijs**
```
2015-03-26T16:52:55.357Z 31157 TID-13s8m8 WARN: {"retry"=>true, "queue"=>"default", "class"=>"DiscussionUpdateWorker", "args"=>["https://cole2.uconline.edu/", "317592"], "jid"=>"1a85273dc687ed75ad24cb74", "enqueued_at"=>1426721200.1744304, "error_message"=>"undefined method `each' for \"\":String", "error_class"=>"NoMethodError", "failed_at"=>1427388775.3558698, "retry_count"=>0}
2015-03-26T16:52:55.357Z 31157 TID-13s8m8 WARN: undefined method `each' for "":String
2015-03-26T16:52:55.357Z 31157 TID-13s8m8 WARN: /home/app_calcentral/datacultures/app/services/canvas/discussion_entries_processor.rb:16:in `call'
/home/app_calcentral/datacultures/app/services/canvas/paged_api_processor.rb:23:in `call'
/home/app_calcentral/datacultures/app/services/canvas/discussion_topics_processor.rb:58:in `block in call'
/home/app_calcentral/datacultures/app/services/canvas/discussion_topics_processor.rb:18:in `each'
/home/app_calcentral/datacultures/app/services/canvas/discussion_topics_processor.rb:18:in `call'
/home/app_calcentral/datacultures/app/services/canvas/paged_api_processor.rb:23:in `call'
/home/app_calcentral/datacultures/app/workers/discussion_update_worker.rb:10:in `perform'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:75:in `execute_job'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/logging.rb:22:in `with_context'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:129:in `block in invoke'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `call'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/middleware/chain.rb:132:in `invoke'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:51:in `block in process'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:98:in `stats'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/sidekiq-3.3.0/lib/sidekiq/processor.rb:50:in `process'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `public_send'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/calls.rb:122:in `dispatch'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in `block in task'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
/home/app_calcentral/.rvm/gems/ruby-2.1.1@datacultures/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
```

### CODE REVIEW

**Comment by paulkerschen** [comment]
@nicolaasmatthijs : The change looks good, but Travis is choking on an unrelated style error in the JS. Can we do a separate PR to fix that issue, and then rebase this one before merge?

**Comment by christianv** [comment]
@nicolaasmatthijs would it be possible to list the jira number?

**Comment by nicolaasmatthijs** [comment]
@paulkerschen : I had already pushed a fix for the JS styling when you commented. The build has now succeeded. Back to you.

**Comment by nicolaasmatthijs** [comment]
https://jira.ets.berkeley.edu/jira/browse/CYB-467

**Pull request merged**
