### PR TITLE
CYB-400 - Remove jQuery and use Highcharts standalone

### PR DESCRIPTION
**Pull request by nicolaasmatthijs**
This PR switches to Highcharts standalone and removes jQuery again from the project. The issue I was experiencing with Highcharts standalone and Angular turned out to be a dependency ordering issue.

Given that this will be rolled out to production soon, it does make sense to keep jQuery out of this as we're not using it for anything else. Note that in the Collabosphere project, I will probably be bringing in jQuery to use it for the things that I don't think we should be using plain Javascript for (e.g. determining the height of the current window, certain types of event binding, etc.)

### CODE REVIEW

**Comment by nicolaasmatthijs** [comment]
Assigning to @raydavis for review

**Comment by raydavis** [comment]
JSHint dissents.

**Comment by nicolaasmatthijs** [comment]
Sorry for that. JSHint has an extremely aggressive configuration on this project :)

Pushed a fix. Waiting for Travis now.

**Comment by nicolaasmatthijs** [comment]
Okay, the build passed :) Back to @raydavis

**Comment by christianv** [comment]
@nicolaasmatthijs if you're using sublime - sublimelinter with jshint & jscs might be useful.

**Pull request merged**
